spring:
    jpa:
        generate-ddl: true
        defer-datasource-initialization: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.auto_quote_keyword: true
    application:
        name: gpu_rentaler_0
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gpu_rentaler_0?characterEncoding=utf8
        username: root
        password: 123456
    sql:
        init:
            encoding: utf8
            data-locations: classpath:data.sql
            mode: always
            continue-on-error: true
    data:
        web:
            pageable:
                one-indexed-parameters: true
    servlet:
        multipart:
            max-file-size: 1000GB
            max-request-size: 1000GB

server:
    servlet:
        context-path: /admin3
    port: 9090


grpc:
    server:
        port: 50052            # 默认端口，如果想每个服务不同端口，可以在启动类配置
        enableReflection: true
        maxInboundMessageSize: 1GB
