admin3:
    events:
        "[com.gpu.rentaler.sys.event.UserLoggedIn]":
            text: '用户登录'
            log-template: ' {{userinfo.username}} 登录系统，登录IP：{{ip}}'
        "[com.gpu.rentaler.sys.event.UserLoggedOut]":
            text: '退出登录'
            log-template: ' {{userinfo.username}} 退出登录'
        "[com.gpu.rentaler.sys.event.UserCreated]":
            text: '创建用户'
            log-template: '用户 {{user.username}} 已创建，用户ID：{{user.id}}'
        "[com.gpu.rentaler.sys.event.UserUpdated]":
            text: '更新用户'
            log-template: '用户 {{user.username}} 已更新，用户ID：{{user.id}}'
        "[com.gpu.rentaler.sys.event.UserDeleted]":
            text: '删除用户'
            log-template: '用户 {{user.username}} 已删除，用户ID：{{user.id}}'
        "[com.gpu.rentaler.sys.event.OrganizationCreated]":
            text: '创建组织架构'
            log-template: '组织架构节点 {{organization.name}} 已创建'
        "[com.gpu.rentaler.sys.event.OrganizationUpdated]":
            text: '更新组织架构'
            log-template: '组织架构节点 {{organization.name}} 已更新'
        "[com.gpu.rentaler.sys.event.OrganizationDeleted]":
            text: '删除组织架构'
            log-template: '组织架构节点 {{organization.name}} 已删除'
        "[com.gpu.rentaler.sys.event.RoleCreated]":
            text: '创建角色'
            log-template: '角色 {{role.name}} 已创建'
        "[com.gpu.rentaler.sys.event.RoleUpdated]":
            text: '更新角色'
            log-template: '角色 {{role.name}} 已更新'
        "[com.gpu.rentaler.sys.event.RoleDeleted]":
            text: '删除角色'
            log-template: '角色 {{role.name}} 已删除'
        "[com.gpu.rentaler.sys.event.ResourceCreated]":
            text: '创建资源'
            log-template: '资源 {{resource.name}} 已创建'
        "[com.gpu.rentaler.sys.event.ResourceUpdated]":
            text: '更新资源'
            log-template: '资源 {{resource.name}} 已更新'
        "[com.gpu.rentaler.sys.event.ResourceDeleted]":
            text: '删除资源'
            log-template: '资源 {{resource.name}} 删除成功'
        "[com.gpu.rentaler.sys.event.StorageConfigCreated]":
            text: '创建对象存储配置'
            log-template: '对象存储配置 {{config.storageId}} 已创建'
        "[com.gpu.rentaler.sys.event.StorageConfigUpdated]":
            text: '更新对象存储'
            log-template: '对象存储配置 {{config.storageId}} 已更新'
        "[com.gpu.rentaler.sys.event.StorageConfigDeleted]":
            text: '删除对象存储配置'
            log-template: '对象存储配置 {{config.storageId}} 删除成功'
        "[com.gpu.rentaler.sys.event.StorageConfigMarkedAsDefault]":
            text: '标记默认对象存储位置'
            log-template: '对象存储配置 {{config.storageId}} 已标记为默认存储位置'
