spring:
    jpa:
        generate-ddl: true  # 自动生成DDL
        defer-datasource-initialization: true  # 延迟数据源初始化，确保表先创建
        show-sql: true  # 开发环境显示SQL
        hibernate:
            ddl-auto: update  # 自动更新表结构（如果表不存在会自动创建）
        properties:
            hibernate.auto_quote_keyword: true
            hibernate.hbm2ddl.auto: update
    application:
        name: gpu_rentaler_0
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        # createDatabaseIfNotExist=true 会自动创建数据库（如果不存在）
        url: jdbc:mysql://127.0.0.1:3306/gpu_rentaler_0?characterEncoding=utf8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    sql:
        init:
            encoding: utf8
            data-locations: classpath:data.sql  # 数据初始化脚本
            mode: always  # 总是执行SQL脚本
            continue-on-error: true  # 遇到错误继续执行（避免重复插入数据时报错）
    data:
        web:
            pageable:
                one-indexed-parameters: true
    servlet:
        multipart:
            max-file-size: 1000GB
            max-request-size: 1000GB

server:
    servlet:
        context-path: /admin3
    port: 9090


grpc:
    server:
        port: 50052            # 默认端口，如果想每个服务不同端口，可以在启动类配置
        enableReflection: true
        maxInboundMessageSize: 1GB
