CREATE TABLE `gpu_devices` (
                               `id` bigint NOT NULL AUTO_INCREMENT,
                               `device_id` varchar(64) NOT NULL COMMENT 'GPU设备唯一标识符',
                               `server_id` bigint NOT NULL COMMENT '所属服务器ID',
                               `device_index` int NOT NULL COMMENT 'GPU在服务器上的索引位置(0,1,2...)',
                               `brand` enum('NVIDIA','AMD','INTEL') NOT NULL COMMENT 'GPU品牌',
                               `model` varchar(128) NOT NULL COMMENT 'GPU型号 (如RTX 4090, A100)',
                               `architecture` varchar(64) DEFAULT NULL COMMENT 'GPU架构 (如Ampere, RDNA2)',
                               `memory_total` bigint NOT NULL COMMENT 'GPU显存总量(MB)',
                               `memory_type` varchar(32) DEFAULT NULL COMMENT '显存类型 (GDDR6, HBM2等)',
                               `cuda_cores` int DEFAULT NULL COMMENT 'CUDA核心数(NVIDIA专用)',
                               `tensor_cores` int DEFAULT NULL COMMENT 'Tensor核心数(NVIDIA专用)',
                               `base_clock` int DEFAULT NULL COMMENT '基础频率(MHz)',
                               `boost_clock` int DEFAULT NULL COMMENT '加速频率(MHz)',
                               `status` enum('active','inactive','maintenance','error','offline') DEFAULT 'active' COMMENT '设备状态',
                               `health_score` decimal(5,2) DEFAULT '100.00' COMMENT '设备健康度(0-100)',
                               `temperature_limit` int DEFAULT '83' COMMENT '温度限制(°C)',
                               `power_limit` int DEFAULT NULL COMMENT '功耗限制(W)',
                               `is_rentable` tinyint(1) DEFAULT '1' COMMENT '是否可租赁',
                               `hourly_rate` decimal(10,4) NOT NULL COMMENT '每小时租金',
                               `tier` enum('basic','standard','premium','enterprise') DEFAULT 'standard' COMMENT '设备等级',
                               `max_concurrent_users` int DEFAULT '1' COMMENT '最大并发用户数',
                               `last_maintenance` date DEFAULT NULL COMMENT '上次维护日期',
                               `next_maintenance` date DEFAULT NULL COMMENT '下次维护日期',
                               `maintenance_notes` text COMMENT '维护备注',
                               `total_runtime_hours` decimal(12,2) DEFAULT '0.00' COMMENT '总运行时长(小时)',
                               `total_revenue` decimal(15,4) DEFAULT '0.0000' COMMENT '总收入',
                               `rental_count` int DEFAULT '0' COMMENT '租赁次数',
                               `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                               `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                               PRIMARY KEY (`id`),
                               UNIQUE KEY `uk_device_server` (`device_id`,`server_id`),
                               KEY `idx_server_id` (`server_id`),
                               KEY `idx_status` (`status`),
                               KEY `idx_brand_model` (`brand`,`model`),
                               KEY `idx_rentable` (`is_rentable`),
                               KEY `idx_created_time` (`created_time`),
                               KEY `idx_updated_time` (`updated_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='GPU设备基础信息表'

CREATE TABLE `gpu_rentals` (
                               `id` bigint NOT NULL AUTO_INCREMENT,
                               `rental_id` varchar(64) NOT NULL COMMENT '租赁订单号',
                               `user_id` bigint NOT NULL COMMENT '用户ID',
                               `gpu_device_id` bigint NOT NULL COMMENT 'GPU设备ID',
                               `start_time` timestamp NULL DEFAULT NULL COMMENT '开始时间',
                               `end_time` timestamp NULL DEFAULT NULL COMMENT '结束时间',
                               `planned_duration_hours` decimal(8,2) DEFAULT NULL COMMENT '计划使用时长(小时)',
                               `actual_duration_hours` decimal(8,2) DEFAULT NULL COMMENT '实际使用时长(小时)',
                               `hourly_rate` decimal(10,4) NOT NULL COMMENT '每小时费率',
                               `total_cost` decimal(12,4) DEFAULT NULL COMMENT '总费用',
                               `payment_status` enum('unpaid','paid','refunded','partial_refund') DEFAULT 'unpaid',
                               `status` enum('pending','active','completed','cancelled','expired') DEFAULT 'pending',
                               `container_id` varchar(128) DEFAULT NULL COMMENT 'Docker容器ID',
                               `ssh_port` int DEFAULT NULL COMMENT 'SSH端口',
                               `ssh_username` varchar(64) DEFAULT NULL COMMENT 'SSH用户名',
                               `ssh_password_hash` varchar(256) DEFAULT NULL COMMENT 'SSH密码哈希',
                               `peak_gpu_utilization` decimal(5,2) DEFAULT NULL COMMENT '峰值GPU利用率(%)',
                               `avg_gpu_utilization` decimal(5,2) DEFAULT NULL COMMENT '平均GPU利用率(%)',
                               `peak_memory_usage` decimal(5,2) DEFAULT NULL COMMENT '峰值显存使用率(%)',
                               `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                               `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                               PRIMARY KEY (`id`),
                               UNIQUE KEY `uk_rental_id` (`rental_id`),
                               KEY `idx_user_id` (`user_id`),
                               KEY `idx_gpu_device_id` (`gpu_device_id`),
                               KEY `idx_status` (`status`),
                               KEY `idx_start_end_time` (`start_time`,`end_time`),
                               KEY `idx_payment_status` (`payment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='GPU租赁记录表'

CREATE TABLE `gpu_container_relations` (
                                           `id` bigint NOT NULL AUTO_INCREMENT,
                                           `gpu_device_id` bigint NOT NULL COMMENT 'GPU设备ID',
                                           `container_id` varchar(128) NOT NULL COMMENT '容器ID',
                                           `user_id` bigint NOT NULL COMMENT '用户ID',
                                           `rental_id` bigint NOT NULL COMMENT '租赁ID',
                                           `container_name` varchar(128) DEFAULT NULL COMMENT '容器名称',
                                           `image_name` varchar(256) DEFAULT NULL COMMENT '镜像名称',
                                           `container_status` enum('creating','running','paused','stopped','error') DEFAULT 'creating',
                                           `gpu_device_index` int DEFAULT NULL COMMENT 'GPU设备索引',
                                           `cuda_visible_devices` varchar(64) DEFAULT NULL COMMENT 'CUDA可见设备',
                                           `gpu_memory_limit_mb` bigint DEFAULT NULL COMMENT 'GPU显存限制(MB)',
                                           `ssh_port` int DEFAULT NULL COMMENT 'SSH端口',
                                           `ssh_username` varchar(64) DEFAULT NULL COMMENT 'SSH用户名',
                                           `vnc_port` int DEFAULT NULL COMMENT 'VNC端口(如果需要)',
                                           `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                                           `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                           PRIMARY KEY (`id`),
                                           UNIQUE KEY `uk_container_gpu` (`container_id`,`gpu_device_id`),
                                           KEY `idx_gpu_device_id` (`gpu_device_id`),
                                           KEY `idx_user_id` (`user_id`),
                                           KEY `idx_rental_id` (`rental_id`),
                                           KEY `idx_container_status` (`container_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='GPU-容器关系表'

CREATE TABLE `gpu_status_monitor` (
                                      `id` bigint NOT NULL AUTO_INCREMENT,
                                      `gpu_device_id` bigint NOT NULL COMMENT 'GPU设备ID',
                                      `current_user_id` bigint DEFAULT NULL COMMENT '当前使用用户ID',
                                      `is_occupied` tinyint(1) DEFAULT '0' COMMENT '是否被占用',
                                      `utilization_gpu` decimal(5,2) DEFAULT '0.00' COMMENT 'GPU利用率(%)',
                                      `utilization_memory` decimal(5,2) DEFAULT '0.00' COMMENT '显存利用率(%)',
                                      `memory_used_mb` bigint DEFAULT '0' COMMENT '已使用显存(MB)',
                                      `memory_free_mb` bigint DEFAULT '0' COMMENT '可用显存(MB)',
                                      `temperature_gpu` int DEFAULT NULL COMMENT 'GPU温度(°C)',
                                      `temperature_memory` int DEFAULT NULL COMMENT '显存温度(°C)',
                                      `power_draw` int DEFAULT NULL COMMENT '实时功耗(W)',
                                      `fan_speed` int DEFAULT NULL COMMENT '风扇转速(%)',
                                      `clock_graphics_mhz` int DEFAULT NULL COMMENT '图形核心频率(MHz)',
                                      `clock_memory_mhz` int DEFAULT NULL COMMENT '显存频率(MHz)',
                                      `process_count` int DEFAULT '0' COMMENT '运行的GPU进程数',
                                      `monitor_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '监控时间点',
                                      `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                                      `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                      PRIMARY KEY (`id`),
                                      KEY `idx_gpu_device_time` (`gpu_device_id`,`monitor_time`),
                                      KEY `idx_current_user` (`current_user_id`),
                                      KEY `idx_occupied` (`is_occupied`),
                                      KEY `idx_monitor_time` (`monitor_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='GPU实时状态监控表'

CREATE TABLE `gpu_usage_history` (
                                     `id` bigint NOT NULL AUTO_INCREMENT,
                                     `rental_id` bigint NOT NULL COMMENT '租赁记录ID',
                                     `gpu_device_id` bigint NOT NULL COMMENT 'GPU设备ID',
                                     `user_id` bigint NOT NULL COMMENT '用户ID',
                                     `start_time` timestamp NOT NULL COMMENT '使用开始时间',
                                     `end_time` timestamp NOT NULL COMMENT '使用结束时间',
                                     `duration_seconds` int NOT NULL COMMENT '使用时长(秒)',
                                     `avg_utilization` decimal(5,2) DEFAULT NULL COMMENT '平均利用率(%)',
                                     `max_utilization` decimal(5,2) DEFAULT NULL COMMENT '最大利用率(%)',
                                     `avg_memory_usage` decimal(5,2) DEFAULT NULL COMMENT '平均显存使用率(%)',
                                     `max_memory_usage` decimal(5,2) DEFAULT NULL COMMENT '最大显存使用率(%)',
                                     `billable_seconds` int DEFAULT NULL COMMENT '可计费时长(秒)',
                                     `billing_rate` decimal(10,6) DEFAULT NULL COMMENT '计费费率(每秒)',
                                     `billing_amount` decimal(10,4) DEFAULT NULL COMMENT '计费金额',
                                     `task_type` varchar(64) DEFAULT NULL COMMENT '任务类型',
                                     `process_name` varchar(128) DEFAULT NULL COMMENT '主要进程名',
                                     `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                                     `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                     PRIMARY KEY (`id`),
                                     KEY `idx_rental_id` (`rental_id`),
                                     KEY `idx_gpu_device_id` (`gpu_device_id`),
                                     KEY `idx_user_id` (`user_id`),
                                     KEY `idx_time_range` (`start_time`,`end_time`),
                                     KEY `idx_billing` (`billable_seconds`,`billing_amount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='GPU使用历史表'

CREATE TABLE `server_gpu_relations` (
                                        `id` bigint NOT NULL AUTO_INCREMENT,
                                        `server_id` bigint NOT NULL COMMENT '服务器ID',
                                        `gpu_device_id` bigint NOT NULL COMMENT 'GPU设备ID',
                                        `slot_position` int DEFAULT NULL COMMENT 'GPU在服务器中的插槽位置',
                                        `pcie_slot` varchar(16) DEFAULT NULL COMMENT 'PCIe插槽信息',
                                        `relation_status` enum('active','inactive','migrating') DEFAULT 'active',
                                        `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                                        `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                        PRIMARY KEY (`id`),
                                        UNIQUE KEY `uk_server_gpu` (`server_id`,`gpu_device_id`),
                                        KEY `idx_server_id` (`server_id`),
                                        KEY `idx_gpu_device_id` (`gpu_device_id`),
                                        KEY `idx_relation_status` (`relation_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='服务器-GPU关系表'

CREATE TABLE `user_gpu_rental_relations` (
                                             `id` bigint NOT NULL AUTO_INCREMENT,
                                             `user_id` bigint NOT NULL COMMENT '用户ID',
                                             `gpu_device_id` bigint NOT NULL COMMENT 'GPU设备ID',
                                             `rental_id` bigint NOT NULL COMMENT '租赁记录ID',
                                             `relation_type` enum('primary','shared','backup') DEFAULT 'primary' COMMENT '关系类型',
                                             `access_level` enum('read','write','admin') DEFAULT 'write',
                                             `resource_quota` json DEFAULT NULL COMMENT 'JSON格式的资源配额信息',
                                             `start_time` timestamp NOT NULL,
                                             `end_time` timestamp NULL DEFAULT NULL,
                                             `relation_status` enum('pending','active','suspended','expired') DEFAULT 'pending',
                                             `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                                             `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                             PRIMARY KEY (`id`),
                                             KEY `idx_user_id` (`user_id`),
                                             KEY `idx_gpu_device_id` (`gpu_device_id`),
                                             KEY `idx_rental_id` (`rental_id`),
                                             KEY `idx_relation_status` (`relation_status`),
                                             KEY `idx_time_range` (`start_time`,`end_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户-GPU租赁关系表'

