version: '3.8'

services:
    rentaler-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rentaler-app

        ports:
            - "9091:9090"    # Spring Boot 应用端口
            - "50051:50051"  # gRPC 通信端口

        environment:
            # 数据库连接（宿主机）
            SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/gpu_rentaler_0?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: 123456

            # JVM 参数
            JAVA_OPTS: -Xms512m -Xmx1024m -Dfile.encoding=UTF-8

        volumes:
            - "D:/docker-volumes/gpu/files:/app/files"     # 应用数据目录（如缓存、导出）

        extra_hosts:
            - "host.docker.internal:host-gateway"

        restart: unless-stopped

        network_mode: bridge
