services:
    nvidia-container:
        image: virtual-box
        build:
            context: .
            args:
                USERNAME: ${USERNAME:-root}
                USER_PASSWORD: ${USER_PASSWORD:-123456}
        environment:
            - USERNAME=${USERNAME:-root}  # 默认为root
            - USER_PASSWORD=${USER_PASSWORD:-123456}  # 默认为123456
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,utility
        runtime: runc
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        ports:
            - "2224:22"
