server:
    port: 5678

# Spring 基础配置
spring:
    application:
        name: monitor-1  # 应用名称

app:
    uuid:
        # UUID存储文件路径，默认值为./uuid.dat
        file-path: data/app-uuid.dat
        # 文件编码格式，默认UTF-8
        file-charset: UTF-8

grpc:
    server:
        port: 50055             # 默认端口，如果想每个服务不同端口，可以在启动类配置
        enableReflection: true
        maxInboundMessageSize: 1GB
    client:
        backend:
            address: "localhost:50051"
            negotiationType: plaintext  # 明文通信，不使用 TLS
            maxInboundMessageSize: 50MB

ip:
    url:
