server:
    port: 5678

# Spring 基础配置
spring:
    application:
        name: monitor-1  # 应用名称

# Dubbo 配置
dubbo:
    # 注册中心配置
    registry:
        address: zookeeper://127.0.0.1:2181  # 注册中心地址，支持多个以逗号分隔
        timeout: 60000  # 注册中心请求超时时间(毫秒)

    # 协议配置
    protocol:
        name: dubbo  # 协议名称
        port: 20880  # 服务端口，-1表示随机端口
        serialization: hessian2  # 序列化方式

    # 应用配置
    application:
        logger: slf4j  # 日志输出方式

    # 服务消费者配置
    consumer:
        timeout: 3000  # 消费超时时间(毫秒)
        check: false  # 启动时是否检查服务是否存在
        loadbalance: roundrobin  # 负载均衡策略

    scan:
        base-packages: com.gpu.rentaler.service

app:
    uuid:
        # UUID存储文件路径，默认值为./uuid.dat
        file-path: data/app-uuid.dat
        # 文件编码格式，默认UTF-8
        file-charset: UTF-8
